export const LANG_ZH_NAME = 'zh';

export const LANG_ZH_TRANS = {
  'hello world': '节省',
  "Add_lang": "添加语言",
  "arab_lang": "阿拉伯",
  "chn_lang": "中国人",
  "cho_lang": "选择一种语言",
  "com_level": "英语择一种语",
  "btn_delete": "压制",
  "detail": "细节",
  "dsh_lang": "拉伯",
  "eng_lang": "英语",
  "niv_exl": "优秀",
  "Fr_lang": "法国",
  "ger_lang": "法拉伯国",
  "hello": "阿拉伯",
  "niv_int": "细节",
  "lat_lang": "添加语",
  "list_lang": "择一种语",
  "modal_close": "言数量",
  "nbr_lang": "语言数量",
  "niv_pre_int": "语数量",
  "running": "优秀",
  "save": "节省",
  "spn_lang": "选择一种语",
  "spk_level": "口语水平",
  "update": "优秀",
  "wri_level": "口语水平",
  "courant":"添加语言",
};