export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'hello world': 'hola mundo',
    "Add_lang": "afegir un idioma",
  "arab_lang": "arab",
  "chn_lang": "xinès",
  "cho_lang": "choosir la langue",
  "com_level": "comprehension level",
  "btn_delete": "suprimiro",
  "btn_save": "enrestro",
  "detail": "detaill",
  "dsh_lang": "afegir un idioma",
  "eng_lang": "Anglais",
  "niv_exl": "excel-lent",
  "Fr_lang": "francais",
  "ger_lang": "allemand",
  "hello": "Hello world",
  "niv_int": "afegir un idio",
  "lat_lang": "latino",
  "list_lang": "llistes d'idiomes",
  "modal_close": "modal fermos",
  "nbr_lang": "nombre d'idiomes",
  "niv_pre_int": "pre-intermediatos",
  "running": "afegir un idioma",
  "save": "guardar",
  "spn_lang": "espagnol",
  "spk_level": "speaking level",
  "update": "modificar",
  "wri_level": "afegir un idioma",
  "courant":"courant",
};