export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'hello world': 'hello world',
    "Add_lang": "ajouter une langue",
    "arab_lang": "arab",
    "chn_lang": "chinois",
    "cho_lang": "choosir la langue",
    "com_level": "niveau comprehension",
    "btn_delete": "suprimer",
    "btn_save": "Enregistrer",
    "detail": "detail",
    "dsh_lang": "Neerlandais",
    "eng_lang": "Anglais",
    "niv_exl": "excellent",
    "Fr_lang": "francais",
    "ger_lang": "allemand",
    "hello": "Hello world",
    "niv_int": "intermediate",
    "courant":"courant",
    "lat_lang": "latin",
    "list_lang": "listes des languages",
    "modal_close": "modal fermer",
    "nbr_lang": "Number de languages",
    "niv_pre_int": "pre-intermediate",
    "running": "running",
    "save": "enregistrer",
    "spn_lang": "espagnol",
    "spk_level": "niveau parler",
    "update": "modifier",
    "wri_level": "niveau ecrit"
};