export const LANG_NR_NAME = 'nr';

export const LANG_NR_TRANS = {
    'hello world': 'hello world',
    "Add_lang": "aantal talen",
    "arab_lang": "arab",
    "chn_lang": "chinois",
    "cho_lang": "aantal laang",
    "com_level": "coomniveau",
    "btn_delete": "verwijderen",
    "btn_save": "nuiopo",
    "detail": "detail",
    "dsh_lang": "Neerlandais",
    "eng_lang": "Engels",
    "niv_exl": "excellent",
    "Fr_lang": "francais",
    "ger_lang": "Duitse",
    "hello": "Engels",
    "niv_int": "intermediate",
    "courant":"courant",
    "lat_lang": "latin",
    "list_lang": "aantal talen",
    "modal_close": "modal fermer",
    "nbr_lang": "aantal talen",
    "niv_pre_int": "pre-intermediate",
    "running": "running",
    "save": "opnemen",
    "spn_lang": "espagnol",
    "spk_level": "spreekniveau",
    "update": "modifier",
    "wri_level": "niveau ecrit"
};