export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'hello world': 'hola mundo',
    "Add_lang": "ajouter une langue",
  "arab_lang": "arab",
  "chn_lang": "chinois",
  "cho_lang": "choosir la langue",
  "com_level": "comprehension level",
  "btn_delete": "suprimer",
  "detail": "detail",
  "dsh_lang": "Neerlandais",
  "eng_lang": "Anglais",
  "niv_exl": "excellent",
  "Fr_lang": "francais",
  "ger_lang": "allemand",
  "hello": "Hello world",
  "niv_int": "intermediate",
  "lat_lang": "latin",
  "list_lang": "listes des languages",
  "modal_close": "modal fermer",
  "nbr_lang": "Number of languages",
  "niv_pre_int": "pre-intermediate",
  "running": "running",
  "save": "enregistrer",
  "spn_lang": "espagnol",
  "spk_level": "speaking level",
  "update": "modifier",
  "wri_level": "written level",
  "courant":"courant",
};