export const LANG_LA_NAME = 'la';

export const LANG_LA_TRANS = {
    'hello world': 'hello world',
    "Add_lang": "addere lingua",
    "arab_lang": "arab",
    "chn_lang": "chinois",
    "cho_lang": "addere lingua",
    "com_level": "loqui grarer",
    "btn_delete": "suprimer",
    "btn_save": "nuiotos",
    "detail": "detail",
    "dsh_lang": "Neerlandais",
    "eng_lang": "Anglais",
    "niv_exl": "excellent",
    "Fr_lang": "francais",
    "ger_lang": "allemand",
    "hello": "Hello world",
    "niv_int": "intermediate",
    "courant":"courant",
    "lat_lang": "Seres",
    "list_lang": "lis linguarum",
    "modal_close": "modal fermeo",
    "nbr_lang": "numerus linguarum",
    "niv_pre_int": "pre-intermediate",
    "running": "running",
    "save": "enregistrer",
    "spn_lang": "espagnoli",
    "spk_level": "loqui gradu",
    "update": "mutare",
    "wri_level": "Sereser"
};