export const LANG_AR_NAME = 'ar';

export const LANG_AR_TRANS = {
    'hello world': 'hello world',
    "Add_lang": "أضف لغة",
    "arab_lang": "ختر اللغ",
    "chn_lang": "ينى",
    "cho_lang": "ائم اللغات",
    "com_level": "ألمانية",
    "btn_delete": "ألمانية",
    "detail": "ألمانية",
    "dsh_lang": "ائم اللغات",
    "eng_lang": "ألمانية",
    "niv_exl": "ولندي",
    "Fr_lang": "توسط",
    "ger_lang": "ونجور مون",
    "hello": "ائم اللغات",
    "niv_int": "ونجور مون",
    "lat_lang": "latin",
    "list_lang": "لتفاصيل",
    "modal_close": "توسط",
    "nbr_lang": "لتفاصيل",
    "niv_pre_int": "ائم اللغات",
    "running": "توسط",
    "save": "توسط",
    "spn_lang": "ماني",
    "spk_level": "توسط",
    "update": "ونجور مون",
    "wri_level": "ماني",
    "courant":"courant",
};