export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'hello world': 'hello world',
    "Add_lang": "add language",
    "arab_lang": "arab",
    "chn_lang": "chinese",
    "cho_lang": "choose a language",
    "com_level": "comprehension level",
    "btn_delete": "delete",
    "btn_save": "save",
    "detail": "detail",
    "dsh_lang": "german",
    "eng_lang": "englist",
    "niv_exl": "excellent",
    "Fr_lang": "french",
    "ger_lang": "german",
    "hello": "Hello world",
    "niv_int": "intermediate",
    "lat_lang": "latin",
    "list_lang": "list of language",
    "modal_close": "modal closed",
    "nbr_lang": "Number of languages",
    "niv_pre_int": "pre-intermediate",
    "running": "running",
    "save": "save",
    "spn_lang": "spanish",
    "spk_level": "speaking level",
    "update": "update",
    "wri_level": "written level",
    "courant":"current",
};